name: ci

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  prepack:
      name: bump-formula
      runs-on: macos-latest
      steps: 
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Bump Version
        run: bash test.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Automatic brew bump version"
          add: .
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}